camunda:
  autoDeploy:
    bpmnResources: classpath*:*-c7.bpmn
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
      async-response-timeout: 1000 # Defines the maximum duration of the long-polling request
      worker-id: spring-boot-client # Identifies the worker towards the Engine
  #      basic-auth: # Configure if REST API is secured with basic authentication
  #        username: my-username
  #        password: my-password
      subscriptions:
        start-c8-instance: # This topic name must match the respective `@ExternalTaskSubscription`
          lock-duration: 10000 # Defines for how long the External Tasks are locked until they can be fetched again
          variable-names:
              - bpmnProcessId
              - version
              - payload
        message-to-c8:
          lock-duration: 10000
          variable-names: # Defines the names of the process variables that are to be fetched
            - messageName
            - correlationKey
            - payload
        signal-to-c8:
          lock-duration: 10000
          variable-names:
            - signalName
            - payload
        error-message-c8:
          lock-duration: 10000
          variable-names:
            - errorCode
            - errorMessage
        do-something:
          lock-duration: 10000

zeebe.client:
  cloud:
    region: bru-2
    clusterId: ece93f65-1e70-4c01-b8c9-9480d7159c8b
    clientId: sOZ0z8FMJRXadrGiItviYSm2iL-CVy7b
    clientSecret: Bzi4cPCbJBVwzta~k4BoOe0c7KjoFBiFWPkArjSNKJeU34hHy8LssaBsKOMm.P~z


server:
  port: 8081